<!--TAGS-->
---
pagetitle: "Lineare Algebra II"
# page-layout: custom
# when using "page-layout :custom" it just doesnt load the sidebar
# section-divs: false
toc: true
# toc means table of contents, thats a link to all sections
# when using the quarto standart page layout the table of contents shows on the right # side of the screen :)
description: | 
  Vorlesungsnotizen zur Vorlesung Lineare Algebra 2 bei Dr Dahmen im SS24
#hide-description: true
---
<!--/TAGS-->

# Willkommen zu meinen Vorlesungsnotizen für Lineare Algebra 2

Hallo und herzlich willkommen auf meiner Seite! Hier findet ihr meine Vorlesungsnotizen zur Vorlesung "Lineare Algebra 2", die ich im Sommersemester 2024 bei Herrn Dr. Dahmen besucht habe. Diese Sammlung von Notizen entstand während der Vorlesung und ist in verschiedene Themengebiete unterteilt, die wir im Laufe des Semesters behandelt haben. Ich hoffe, dass sie auch anderen Studierenden bei der Prüfungsvorbereitung oder einfach beim Verstehen der Konzepte hilfreich sein können.

In der Vorlesung haben wir viele spannende Themen der linearen Algebra vertieft, die auf den Inhalten aus Lineare Algebra 1 aufbauen. Zu den wichtigsten Themenbereichen gehören:

- **Skalarprodukte:** Hier ging es um Vektoren, Längen, Winkel und die Bedeutung von Orthogonalität. Wir haben unter anderem das Skalar- und Kreuzprodukt behandelt sowie Konzepte wie Orthogonalprojektionen und Orthonormalbasen besprochen.

- **Isometrien und Homomorphismen:** Ein weiteres großes Thema waren Isometrien und deren Eigenschaften. Dabei ging es zum Beispiel um die orthogonale und unitäre Gruppe sowie um spezielle Matrizen wie selbstadjungierte und normale Matrizen. Auch der Spektralsatz spielte eine wichtige Rolle.

- **Bilinearformen und quadratische Formen:** Zum Ende der Vorlesung haben wir uns intensiver mit Bilinearformen und quadratischen Formen beschäftigt. Dazu gehören ihre symmetrischen Eigenschaften, ihre Diagonalisierbarkeit und Anwendungen wie die Untersuchung von Quadriken.

Diese Notizen sind natürlich keine offiziellen Materialien, sondern entstanden aus meiner Sicht als Student während der Vorlesung. Trotzdem hoffe ich, dass sie dir helfen, die Themen besser zu verstehen und dich auf Klausuren vorzubereiten. Die Inhalte sind nach Kapiteln und Unterkapiteln sortiert, sodass du leicht navigieren kannst.

Viel Erfolg beim Lernen – ich hoffe, die Notizen sind für dich genauso nützlich wie für mich!
-Philip